M48
; DRILL file {KiCad (6.0.7)} date Sun Sep 18 10:38:16 2022
; FORMAT={-:-/ absolute / metric / decimal}
; #@! TF.CreationDate,2022-09-18T10:38:16-04:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,(6.0.7)
; #@! TF.FileFunction,NonPlated,1,2,NPTH
FMAT,2
METRIC
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C5.080
%
G90
G05
T1
X90.17Y-68.58
X90.17Y-119.38
X153.67Y-68.58
X153.67Y-119.38
T0
M30
